coverage:
  precision: 1
  round: up
  range: "75...95"
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 90%
    changes: true
comment:
  layout: "header, changes"
  behavior: default
  require_changes: true